<center> <H1> Matrices Recap <H1/><center/>

Link to the article : https://medium.com/@soulawalid/complete-guide-for-matrices-2c324242276c

## Types of Matrices

### Square

In [4]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Rectangular

In [5]:
import numpy as np
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Identity Matrix

In [6]:
import numpy as np
matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Matrix Arithmetic Operations

### Addition

In [7]:
import numpy as np

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)

result = matrix_a + matrix_b

print("\nResult of adding Matrix A and Matrix B:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of adding Matrix A and Matrix B:
[[ 6  8]
 [10 12]]


### Subtraction

In [13]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  
B = np.array([[7,8], [9,10], [11,12]])  

C = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nDot Product (Matrix Product):")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product (Matrix Product):
[[ 58  64]
 [139 154]]


### Dot Product

In [24]:
import numpy as np

A = np.array([1000, 400, 1200])  
B = np.array([[30,40,50], [5,10,15], [2,5,7]])  

C = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nDot Product:")
print(C)

Matrix A:
[1000  400 1200]

Matrix B:
[[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]

Dot Product (Matrix Product):
[34400 50000 64400]


### Matrix Multiplication by a scalar

In [16]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  
B = 2

C = A*B

print("Matrix A:")
print(A)
print("\nResult of Matrix Multiplication:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Result of Matrix Multiplication:
[[ 2  4  6]
 [ 8 10 12]]


### Matrix-Matrix Multiplication

In [19]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])  
B = np.array([[7,8], [9,10], [11,12]])  

C = A @ B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nDot Product (Matrix Product):")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product (Matrix Product):
[[ 58  64]
 [139 154]]


## Determinant of  a Matrix

### 2x2

In [25]:
# Define the 2x2 matrix
matrix = [[3, 4], [2, 1]]

# Calculate the determinant using the formula: ad - bc
det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

print("The determinant of the matrix is:", det)

The determinant of the matrix is: -5


In [27]:
import numpy as np

matrix = [[3, 4], [2, 1]]
det = np.linalg.det(matrix)

print("The determinant of the matrix is:", det)

The determinant of the matrix is: -5.000000000000001


### 3x3

In [29]:
import numpy as np

matrix = [[3, 4,1], [2, 1,5],[1, 3,7]]
det = np.linalg.det(matrix)

print("The determinant of the matrix is:", det)
#The determinant of the matrix is: -55.000000000000014

The determinant of the matrix is: -55.000000000000014


## Inversion

In [6]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Compute the determinant to check if the matrix is invertible
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    # Calculate the inverse of the matrix
    A_inv = np.linalg.inv(A)
    print("Inverse of matrix A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Determinant of A: 0.9999999999999987
Inverse of matrix A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
